#!/bin/sh
# git proxy wrapper
# need to install nc first
# put this file in directories in $PATH

_proxy="<socks proxy>"
_proxyport="1080"

case $1 in
    # Direct connect without proxy
    *.intel.com|192.168.*|127.0.*|localhost|10.*)
      METHOD="-X connect"
    ;;
    *)
      METHOD="-X 5 -x $_proxy:$_proxyport"
    ;;
esac

/bin/nc.openbsd $METHOD $*
